import { initializeTestEnvironment, assertFails, assertSucceeds } from "@firebase/rules-unit-testing";
import { doc, setDoc, getDoc, addDoc, collection, deleteDoc, updateDoc } from "firebase/firestore";
import fs from "fs";
const env = await initializeTestEnvironment({ projectId: "demo-sr", firestore: { rules: fs.readFileSync(new URL("../firestore.rules", import.meta.url), "utf8"), host: "127.0.0.1", port: 8080 } });
const A = env.authenticatedContext("alice", { email: "alice@a.com" }).firestore();
const B = env.authenticatedContext("bob", { email: "bob@b.com" }).firestore();
const C = env.authenticatedContext("carol", { email: "carol@a.com" }).firestore();
const anon = env.unauthenticatedContext().firestore();
let pass = 0, fail = 0;
const t = async (name, p) => { try { await p; pass++; console.log("✓", name); } catch (e) { fail++; console.log("✗", name, e.message.slice(0, 120)); } };

await t("alice creates org", assertSucceeds(setDoc(doc(A, "orgs/orgA"), { name: "A", ownerUid: "alice", plan: "free" })));
await t("cannot create org with paid plan", assertFails(setDoc(doc(A, "orgs/orgX"), { name: "X", ownerUid: "alice", plan: "business" })));
await t("alice becomes owner", assertSucceeds(setDoc(doc(A, "orgs/orgA/members/alice"), { email: "alice@a.com", role: "owner" })));
await t("bob cannot make himself owner of orgA", assertFails(setDoc(doc(B, "orgs/orgA/members/bob"), { email: "bob@b.com", role: "owner" })));
await t("alice sets profile", assertSucceeds(setDoc(doc(A, "users/alice"), { email: "alice@a.com", orgId: "orgA" })));
await t("bob cannot point profile to orgA", assertFails(setDoc(doc(B, "users/bob"), { orgId: "orgA" })));
await t("alice adds store", assertSucceeds(setDoc(doc(A, "orgs/orgA/stores/s1"), { name: "x", lat: 16.8, lng: 96.1, brandId: "b" })));
await t("invalid lat rejected", assertFails(setDoc(doc(A, "orgs/orgA/stores/s2"), { name: "x", lat: 200, lng: 96.1 })));
await t("bob cannot read orgA stores", assertFails(getDoc(doc(B, "orgs/orgA/stores/s1"))));
await t("bob cannot write orgA stores", assertFails(setDoc(doc(B, "orgs/orgA/stores/s9"), { lat: 1, lng: 1 })));
await t("anon cannot read", assertFails(getDoc(doc(anon, "orgs/orgA"))));
await t("bob cannot invite into orgA", assertFails(setDoc(doc(B, "invites/bob@b.com"), { orgId: "orgA", role: "admin" })));
await t("alice invites carol as viewer", assertSucceeds(setDoc(doc(A, "invites/carol@a.com"), { orgId: "orgA", role: "viewer" })));
await t("carol reads her invite", assertSucceeds(getDoc(doc(C, "invites/carol@a.com"))));
await t("bob cannot read carol's invite", assertFails(getDoc(doc(B, "invites/carol@a.com"))));
await t("carol cannot join as editor (invited viewer)", assertFails(setDoc(doc(C, "orgs/orgA/members/carol"), { role: "editor" })));
await t("carol joins as viewer", assertSucceeds(setDoc(doc(C, "orgs/orgA/members/carol"), { email: "carol@a.com", role: "viewer" })));
await t("carol (viewer) reads stores", assertSucceeds(getDoc(doc(C, "orgs/orgA/stores/s1"))));
await t("carol (viewer) cannot write stores", assertFails(setDoc(doc(C, "orgs/orgA/stores/s3"), { lat: 1, lng: 1 })));
await t("carol cannot promote herself", assertFails(updateDoc(doc(C, "orgs/orgA/members/carol"), { role: "admin" })));
await t("alice cannot change plan", assertFails(updateDoc(doc(A, "orgs/orgA"), { plan: "business" })));
await t("alice renames org", assertSucceeds(updateDoc(doc(A, "orgs/orgA"), { name: "A2" })));
await t("usage not writable by clients", assertFails(setDoc(doc(A, "orgs/orgA/usage/2026-09"), { placesSearches: 0 })));
await t("carol deletes her invite", assertSucceeds(deleteDoc(doc(C, "invites/carol@a.com"))));
console.log(`\n${pass} passed, ${fail} failed`);
await env.cleanup(); process.exit(fail ? 1 : 0);
